Repository renew-wireless/RENEWLab, pull requests merged in 2020-12, with the labels that each got.

#53 Fix the single gain feature for UHD
  CC/Sounder/Radio.cc
  README.md
Labels: bug

#55 Plot hardcode fix
  PYTHON/IrisUtils/plot_hdf5.py
  README.md
Labels: bug

#59 Fix the bug and add snr per user plot
  PYTHON/IrisUtils/plot_hdf5.py
  README.md
Labels: bug

#61 Detect bad base station nodes
  PYTHON/IrisUtils/channel_analysis.py
  PYTHON/IrisUtils/plot_hdf5.py
  README.md
Labels: enhancement

#64 Pilot types
  CC/Sounder/BaseRadioSet-calibrate.cc
  CC/Sounder/BaseRadioSet.cc
  CC/Sounder/ClientRadioSet.cc
  CC/Sounder/Radio.cc
  CC/Sounder/comms-lib.cc
  CC/Sounder/config.cc
  CC/Sounder/include/comms-lib.h
  CC/Sounder/include/config.h
  CC/Sounder/recorder_worker.cc
  CC/Sounder/tests/comms-func/test-main.cc
  PYTHON/IrisUtils/channel_analysis.py
  PYTHON/IrisUtils/generate_sequence.py
  PYTHON/IrisUtils/hdf5_lib.py
  PYTHON/IrisUtils/plot_hdf5.py
  README.md
Labels: bug, enhancement
